### ISSUE TITLE
[folderview]: right-click: change entry "Folderview Settings" to "Desktop Settings" (or change Folderview to become the default Desktop containment anyway)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#23]
some sample userfeedback:
https://forums.mauilinux.org/showthread.php?tid=23855&pid=38817#pid38817

**Comment by notmart** [comment]
on 5.8 the context menu says "Desktop settings" in case of folderview as well, look and feel packages support the concept of default containment, so a distribution can specify what to use (so a folder containment would be created in cases of new external monitor connected and what not)

**Comment by star-buck** [comment]
closing since done.
(we imo still should think about changing folderview to become the default desktop containment again since thats among one of the most asked questions from people about the unusual/confusing behaviour of plasmas current default containment).
