### ISSUE TITLE
[window decoration kcm]: customize button sometimes misaligned

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#34]
![screenshot_20161022_155924](https://cloud.githubusercontent.com/assets/840070/19619876/b8d190d0-9870-11e6-871d-500637e6b63e.png)

**Comment by star-buck** [comment]
e.g. the Carbon button is located at "Maui" top right corner...

**Comment by davidedmundson** [comment]
On review: https://phabricator.kde.org/D3526

**Comment by davidedmundson** [comment]
Merged. Will be in 5.8.5

**Comment by star-buck** [comment]
works!
