### ISSUE TITLE
[discover]: change "Link to product page" for KDE Store items from backend URL to frontend URL

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#38]
For Addons like Widgets that come from the Store, the link given to the product page is currently pointing to api.kde-look.org backend, I suggest to change it to frontend.

This can simply be changed to point to the frontend by replacing "api.kde-look.org" with "store.kde.org" while keeping everything else following the same, e.g.:
api.kde-look.org/p/1234567890 -> store.kde.org/p/1234567890

**Comment by star-buck** [comment]
Here is an example of where it occurs:
![screenshot_20161126_093553](https://cloud.githubusercontent.com/assets/840070/20639221/83faabae-b3bd-11e6-915a-e97ee87c51b5.png)

**Comment by aleixpol** [comment]
Hi, I've been looking into the issue, it's OCS suggesting this page itself. It would be better if this could be solved at the server side.

This can be checked easily by: `curl "https://api.kde-look.org/ocs/v1/content/data?categories=155&distribution&license&search&sortmode=new&page=1&pagesize=100" | xmllint --format - | less`

You'll see tuples like this:
```
    <content details="summary">
      <id>1080441</id>
      <name>Pondus (nb)</name>
      <version>0.9</version>
      <typeid>155</typeid>
      <typename>Plasma Comics</typename>
      <language/>
      <personid>unbob</personid>
      <created>2009-08-01T10:25:11-04:00</created>
      <changed>2016-01-19T13:21:25-05:00</changed>
      <downloads>151</downloads>
      <score>68</score>
      <summary/>
      <description>Pondus av Frode Øverli.</description>
      <comments>0</comments>
      <preview1>https://api.kde-look.org/p/1080441</preview1>
      <detailpage>https://api.kde-look.org/p/1080441</detailpage>
      <previewpic1>https://cn.pling.com/cache/770x540/img//hive/content-pre1/109395-1.png</previewpic1>
      <previewpic2>https://cn.pling.com/cache/770x540/img//hive/content-pre1/109395-1.png</previewpic2>
      <smallpreviewpic1>https://cn.pling.com/cache/100x100/img//hive/content-pre1/109395-1.png</smallpreviewpic1>
      <smallpreviewpic2>https://cn.pling.com/cache/100x100/img//hive/content-pre1/109395-1.png</smallpreviewpic2>
      <downloadway1>1</downloadway1>
      <downloadtype1/>
      <downloadprice1>0</downloadprice1>
      <downloadlink1>https://dl.opendesktop.org/api/files/download/id/1460970884/109395-pondus_nb.comic</downloadlink1>
      <downloadname1>109395-pondus_nb.comic</downloadname1>
      <downloadsize1>2</downloadsize1>
      <downloadgpgfingerprint1/>
      <downloadgpgsignature1/>
      <downloadpackagename1/>
      <downloadrepository1/>
    </content>
```

Especially this line: `<detailpage>https://api.kde-look.org/p/1080441</detailpage>`

If this is fixed there, it will work correctly on all clients.

**Comment by star-buck** [comment]
should be changed.
