### ISSUE TITLE
question: is wayland starting default on kde neon 5.8.90?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#47]
because i cant seem to find anything under kinfocenter, though it certainly feels very smooth...
but then it seems almost too perfect, so i guess not? ;)
![screenshot_20170112_223830](https://cloud.githubusercontent.com/assets/840070/21909334/dfb4d030-d917-11e6-982c-da2f46bf158f.png)

**Comment by jriddell** [comment]
Not yet but with Plasma 5.9 nearly out it's about time to do that.  The main issue I think is with fancy graphics cards, I get people saying it doesn't work with nvidia or the like.  I'd like to make the change at the Plasma sprint in a couple of weeks after getting feedback from Plasma devs.

In the mean time just apt install plasma-wayland-desktop and log out and select the wayland session on log in.

**Comment by star-buck** [comment]
Makes sense.
